### ISSUE TITLE
NaN with entropy

### ISSUE THREAD

**Issue by varsis** [minhnhat93/ssl-lasagne#3]
After running in debug mode the following is the stack trace:

``` sh
Traceback (most recent call last):
  File "necklace/semisupervised_lasagne.py", line 179, in <module>
    train_err = train_fn(inputs, targets, labeled)
  File "/Users/chris/Library/Python/2.7/lib/python/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/Users/chris/Library/Python/2.7/lib/python/site-packages/theano/compile/debugmode.py", line 2313, in deco
    return f()
  File "/Users/chris/Library/Python/2.7/lib/python/site-packages/theano/compile/debugmode.py", line 2053, in f
    specific_hint=hint2)
theano.compile.debugmode.InvalidValueError: InvalidValueError
        type(variable) = TensorType(float32, matrix)
        variable       = HostFromGpu.0
        type(value)    = <type 'numpy.ndarray'>
        dtype(value)   = float32
        shape(value)   = (200, 10)
        value          = [[             nan   7.31889578e-03              nan ...,   2.35110950e-02
    2.84437276e-02       
        min(value)     = nan
        max(value)     = nan
        isfinite       = False
        client_node    = None
        hint           = perform output
        specific_hint  = non-finite elements not allowed
        context        = ...
  HostFromGpu [id A] ''   
   |GpuElemwise{pow,no_inplace} [id B] ''   
     |W [id C]
     |CudaNdarrayConstant{[[ 2.]]} [id D]
```

Will look into this more once I learn how everything is put together with theano / lasagne.

This is here just in case, or if someone has a simple solution.

**Comment by minhnhat93** [comment]
Reduce the learning rate helped. Closed
